events { }

http {
    upstream gateway {
        server gateway_service:8080;
    }

    server {
        listen 80;

        # Ruta para Student
        location /api/student/ {
            proxy_pass http://gateway;
        }

        # Ruta para Course
        location /api/course/ {
            proxy_pass http://gateway;
        }

        # Ruta por defecto (Angular u otra UI)
        location / {
            proxy_pass http://gateway;
        }
    }
}
